# Generated by Django 4.2.1 on 2024-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='images')),
                ('registration_number', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_description', models.TextField()),
                ('part_exchange', models.BooleanField(default=False)),
                ('car_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_door', models.IntegerField()),
                ('gear_box', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=100)),
                ('engine_position', models.CharField(max_length=100)),
                ('aspiration', models.CharField(max_length=100)),
                ('engine_size', models.CharField(max_length=100)),
                ('cylinder_layout', models.CharField(max_length=100)),
                ('fuel_consumption', models.CharField(max_length=100)),
                ('health', models.CharField(max_length=100)),
                ('cylinder', models.IntegerField()),
                ('owners', models.IntegerField()),
                ('top_speed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driven_wheels', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('telephone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'car_registration',
                'ordering': ['id'],
            },
        ),
    ]
